import type { ConversationData, ConversationMessage, ExportOptions } from './types'

const INLINE_CSS = `
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: #f5f5f5;
  color: #1a1a1a;
  line-height: 1.6;
}
.container { max-width: 800px; margin: 0 auto; padding: 24px 16px; }
header { margin-bottom: 24px; }
header h1 { font-size: 1.5rem; font-weight: 600; margin-bottom: 4px; }
.meta { font-size: 0.85rem; color: #666; }
.messages { display: flex; flex-direction: column; gap: 12px; }
.message {
  padding: 12px 16px;
  border-radius: 12px;
  max-width: 85%;
  word-wrap: break-word;
}
.message.user {
  background: #6366F1;
  color: #fff;
  align-self: flex-end;
  border-bottom-right-radius: 4px;
}
.message.assistant {
  background: #e5e5e5;
  color: #1a1a1a;
  align-self: flex-start;
  border-bottom-left-radius: 4px;
}
.message-header {
  font-size: 0.8rem;
  margin-bottom: 6px;
  opacity: 0.8;
}
.message-content { white-space: pre-wrap; }
.message-content code {
  background: rgba(0,0,0,0.08);
  padding: 2px 6px;
  border-radius: 4px;
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 0.9em;
}
.message.user .message-content code { background: rgba(255,255,255,0.2); }
.message-content pre {
  background: #2d2d2d;
  color: #f8f8f2;
  padding: 12px;
  border-radius: 8px;
  overflow-x: auto;
  margin: 8px 0;
}
.message-content pre code {
  background: none;
  padding: 0;
  color: inherit;
}
footer {
  margin-top: 32px;
  padding-top: 16px;
  border-top: 1px solid #ddd;
  text-align: center;
}
.attribution { font-size: 0.85rem; color: #999; }
@media (max-width: 600px) {
  .container { padding: 12px 8px; }
  .message { max-width: 95%; }
}
`

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function renderBasicMarkdown(text: string): string {
  let html = escapeHtml(text)

  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_match, lang, code) => {
    return `<pre><code class="language-${lang}">${code.trim()}</code></pre>`
  })

  html = html.replace(/`([^`]+)`/g, '<code>$1</code>')

  html = html.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')

  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>')

  html = html.replace(/\n/g, '<br>\n')

  return html
}

function renderMessage(msg: ConversationMessage, includeMetadata: boolean): string {
  const roleClass = msg.role === 'user' ? 'user' : 'assistant'
  const roleLabel = msg.role === 'user' ? 'You' : 'AI'

  const parts: string[] = []
  let header = `<strong>${roleLabel}</strong>`

  if (includeMetadata && msg.aiModeId) {
    header += ` &middot; ${escapeHtml(msg.aiModeId)}`
  }

  if (includeMetadata) {
    const date = new Date(msg.createdAt)
    const ts = isNaN(date.getTime()) ? msg.createdAt : date.toLocaleString()
    header += ` &middot; <em>${escapeHtml(ts)}</em>`
  }

  parts.push(`<div class="message-header">${header}</div>`)
  parts.push(`<div class="message-content">${renderBasicMarkdown(msg.content)}</div>`)

  if (includeMetadata && msg.model) {
    parts.push(`<div class="message-meta" style="font-size:0.75rem;margin-top:4px;opacity:0.6">Model: ${escapeHtml(msg.model)}</div>`)
  }

  return `<div class="message ${roleClass}">${parts.join('\n')}</div>`
}

export class HtmlRenderer {
  render(data: ConversationData, options: ExportOptions): string {
    const messages = options.messageRange
      ? data.messages.slice(options.messageRange.startIndex, options.messageRange.endIndex + 1)
      : data.messages

    const date = new Date()
    const timestamp = date.toLocaleString()

    const messagesHtml = messages.map((msg) => renderMessage(msg, options.includeMetadata)).join('\n')

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(data.title)} — Sibylla Export</title>
  <style>${INLINE_CSS}</style>
</head>
<body>
  <div class="container">
    <header>
      <h1>${escapeHtml(data.title)}</h1>
      <div class="meta">Exported at ${timestamp} | ${messages.length} messages</div>
    </header>
    <div class="messages">
${messagesHtml}
    </div>
    <footer>
      <p class="attribution">Generated by <strong>Sibylla</strong></p>
    </footer>
  </div>
</body>
</html>
`
  }
}
